name: "build"

on:
    push:
    # branches: ["*"]
    pull_request:
        # branches: ["*"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            #
            - name: Action For Semantic Release
              uses: cycjimmy/semantic-release-action@v3.0.0
            #
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - run: |
                  yarn install --frozen-lockfile
                  yarn _ci
            #
            - uses: "marvinpinto/action-automatic-releases@latest"
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  automatic_release_tag: "latest"
                  prerelease: true
                  title: "Development Build"
                  files: |
                      dist/closured*
